name: phone_feature
description: A Flutter package to get battery level, adjust screen brightness, and control device vibration.
version: 0.0.2

homepage: https://github.com/HamzaPolat68/phone_feature
repository: https://github.com/HamzaPolat68/phone_feature.git
license: MIT

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^6.2.3
  screen_brightness: ^2.1.6
  vibration: ^3.1.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
